name: shortiner

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: "${DB_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@db:5434/${DB_DATABASE}?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    restart: always
    volumes:
      - ./logs:/app/logs
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4.0'
          memory: 4g
        reservations:
          memory: 2g
    sysctls:
      net.core.somaxconn: 4096
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 8192
      net.ipv4.tcp_fin_timeout: 15
    ulimits:
      nofile:
        soft: 65536
        hard: 131072

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "${DB_PORT}:5434"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 2g
        reservations:
          memory: 1g
    sysctls:
      net.core.somaxconn: 4096
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 8192
      net.ipv4.tcp_fin_timeout: 15
    ulimits:
      nofile:
        soft: 65536
        hard: 131072
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
