// Package v2 Code generated by swaggo/swag. DO NOT EDIT
package v2

import "github.com/swaggo/swag"

const docTemplatev2 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/report": {
            "post": {
                "description": "Постановка задачи генерации отчета.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "Создать отложенную задачу генерации отчета.",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go_shurtiner_internal_app_model.Params"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ с полной информацией о добавленных ссылках",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/go_shurtiner_internal_app_model.JobQueue"
                            }
                        }
                    },
                    "400": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/go_shurtiner_internal_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/short": {
            "post": {
                "description": "Сокращение ссылок из массива параметров.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "Сократить ссылки от имени зарегистрированного пользователя",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/go_shurtiner_internal_app_model.CreateLink"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ с полной информацией о добавленных ссылках",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/go_shurtiner_internal_app_model.Link"
                            }
                        }
                    },
                    "400": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/go_shurtiner_internal_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/short/{link}": {
            "get": {
                "description": "Поиск оригинальной ссылки по короткому идентификатору.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "Получить информацию по сокращённой ссылке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор сокращённой ссылки",
                        "name": "link",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ с полной информацией о ссылке",
                        "schema": {
                            "$ref": "#/definitions/go_shurtiner_internal_app_model.Link"
                        }
                    },
                    "400": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/go_shurtiner_internal_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "description": "Информация по зарегистрированному пользователю.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получить информацию по зарегистрированному пользователю.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Смещение пагинации",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ с полной информацией о пользователях",
                        "schema": {
                            "$ref": "#/definitions/go_shurtiner_internal_app_model.UserApi"
                        }
                    },
                    "400": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/go_shurtiner_internal_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Информация по всем зарегистрированным пользователям.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получить информацию по зарегистрированным пользователям.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Смещение пагинации",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ с полной информацией о пользователях",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/go_shurtiner_internal_app_model.UserApi"
                            }
                        }
                    },
                    "400": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/go_shurtiner_internal_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "go_shurtiner_internal_app_model.CreateLink": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "go_shurtiner_internal_app_model.JobQueue": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "expire_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "launched_at": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                },
                "params": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "scheduled_started_at": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "go_shurtiner_internal_app_model.Link": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "shortened": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go_shurtiner_internal_app_model.User"
                    }
                }
            }
        },
        "go_shurtiner_internal_app_model.Params": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/json.JSON"
                },
                "scheduledStarted_at": {
                    "type": "integer"
                }
            }
        },
        "go_shurtiner_internal_app_model.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go_shurtiner_internal_app_model.Link"
                    }
                },
                "middlename": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "go_shurtiner_internal_app_model.UserApi": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string"
                },
                "middlename": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "go_shurtiner_internal_http_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {},
                "errors": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "json.JSON": {
            "type": "object"
        }
    }
}`

// SwaggerInfov2 holds exported Swagger Info so clients can modify it
var SwaggerInfov2 = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "Go Shurtiner API",
	Description:      "Go Shurtiner API Swagger",
	InfoInstanceName: "v2",
	SwaggerTemplate:  docTemplatev2,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfov2.InstanceName(), SwaggerInfov2)
}
